version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "25519:25519"
    volumes:
      - uploads_volume:/app/server/uploads
      - ./server/.env:/app/server/.env  # 挂载 .env 文件以持久化 JWT_SECRET
    depends_on:
      mongodb:
        condition: service_healthy  # 等待 mongodb 健康检查通过
    networks:
      - app-network
    restart: unless-stopped  # 添加重启策略
    environment:
      - PORT=25519
      - MONGODB_URI=mongodb://mongodb:27017/stb
      - JWT_SECRET=${JWT_SECRET:?error} # JWT_SECRET 必须是非空环境变量
      - VITE_APP_TITLE=Stb图床 # 图床标题
    expose:
      - 25519
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    healthcheck:  # 添加健康检查
      test: ["CMD", "mongosh", "--eval", "'db.runCommand({ping: 1})'"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped  # 添加重启策略
    container_name: mongodb

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: 
  uploads_volume: 