name: 发布并推送到Telegram

on:
  release:
    types: [published]

jobs:
  notify:
    name: 发布信息推送到Telegram
    runs-on: ubuntu-latest
    steps:
      - name: 发送Telegram通知
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: html
          message: |
            <b>Stb图床程序${{ github.event.release.tag_name }}版本发布</b>

            <b>更新内容:</b>
            ${{ github.event.release.body }}

            <b>压缩包下载:</b><a href="${{ github.event.release.html_url }}">点击下载</a>

            <b>Docker:</b><a href="https://github.com/setube/stb/pkgs/container/stb">点击查看</a>
